Updating main.yaml

diff --git a/.github/workflows/dev-workflows.yaml b/.github/workflows/dev-workflows.yaml
--- a/.github/workflows/dev-workflows.yaml
+++ b/.github/workflows/dev-workflows.yaml
@@ -1,4 +1,3 @@
-
 name: Dev Workflow
 
 on:
@@ -13,7 +12,7 @@ env:
     NEXUS_SOURCE_MAIN: http://faraztest.southeastasia.cloudapp.azure.com:8081/repository/nuget-tag/
     NEXUS_SOURCE_DEV: http://faraztest.southeastasia.cloudapp.azure.com:8081/repository/nuget-snapshot/
     NEXUS_SOURCE_RELEASE: http://faraztest.southeastasia.cloudapp.azure.com:8081/repository/nuget-rc/
-    ARTIFACT_PATH: ""
+    ARTIFACT_PATH: "./output"
     PACKAGE_OUTPUT_DIR: './output'
 
 jobs:
@@ -34,95 +33,102 @@ jobs:
       - name: Build the application
         run: dotnet build netapplication.csproj --configuration Release
 
-      # - name: Pack the NuGet package    
-      #   env:
-      #     NEXUS_SOURCE: http://faraztest.southeastasia.cloudapp.azure.com:8081/repository/nuget-tag/
-      #   run: |
-      #     FOLDER_NAME="netapp"
-      #     VERSION="${GITHUB_REF#refs/tags/}"
-      #     COMMIT_SHA=${{ github.sha }}
-      #     SHORT_SHA=${COMMIT_SHA:0:6}
-      #     echo "CustomPackageId=$VERSION" >> $GITHUB_ENV 
-      #     echo "PackageVersion=$SHORT_SHA" >> $GITHUB_ENV
+      - name: Pack the NuGet package    
+        env:
+          NEXUS_SOURCE: http://faraztest.southeastasia.cloudapp.azure.com:8081/repository/nuget-tag/
+        run: |
+          FOLDER_NAME="netapp"
+          VERSION="${GITHUB_REF#refs/tags/}"
+          COMMIT_SHA=${{ github.sha }}
+          SHORT_SHA=${COMMIT_SHA:0:6}
  
+          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
+            TAG_NAME="${GITHUB_REF#refs/tags/}"
+            git fetch origin main
+            MAIN_COMMIT=$(git rev-parse origin/main)
+            TAG_COMMIT=$(git rev-parse "${GITHUB_REF}")
+            
+            if [[ "$TAG_COMMIT" == "$MAIN_COMMIT" ]]; then
+              export PACKAGE_VERSION="${TAG_NAME}"
+              export PACKAGE_ID="${FOLDER_NAME}-${TAG_NAME}"              
+              echo "PACKAGE_ID=${PACKAGE_ID}" >> $GITHUB_ENV
+              echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
+              dotnet pack netapplication.csproj --configuration Release --output ./output /p:CustomPackageId=$PACKAGE_ID /p:PackageVersion=$PACKAGE_VERSION
+            else
+              echo "Tag can be created only from the main branch."
+              exit 1
+            fi
+         
+            elif [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
+            dotnet pack netapplication.csproj --configuration Release --version-suffix $VERSION --output ./output 
+          
+            elif [[ "${GITHUB_REF}" == "refs/heads/release" ]]; then
+            export PACKAGE_ID="${FOLDER_NAME}-1.0.0-release-${COMMIT_ID}"
+            export PACKAGE_VERSION="1.0.0-release-${COMMIT_ID}"
+            dotnet pack netapplication.csproj --configuration Release --version-suffix $VERSION --output ./output /p:CustomPackageId=$PACKAGE_ID /p:PackageVersion=$PACKAGE_VERSION
+          elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
+            exit 1
+          fi
+
+      - name: Upload Package as Artifact 
+        uses: actions/upload-artifact@v3
+        with:
+          name: nuget-package
+          path: ${{ env.ARTIFACT_PATH }}
+  
+
+      # - name: Set package name and version
+      #   id: set_name
+      #   shell: bash
+      #   run: |
+      #     echo "Checking GITHUB_REF: $GITHUB_REF"
+      #     git config --global --add safe.directory /__w/git-nexus-task/git-nexus-task
+      #     FOLDER_NAME="helloworld"
+
       #     if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
       #       TAG_NAME="${GITHUB_REF#refs/tags/}"
-      #       git fetch origin main
+      #       git fetch --unshallow || true
       #       MAIN_COMMIT=$(git rev-parse origin/main)
       #       TAG_COMMIT=$(git rev-parse "${GITHUB_REF}")
+
       #       if [[ "$TAG_COMMIT" == "$MAIN_COMMIT" ]]; then
-      #         dotnet pack netapplication.csproj --configuration Release --version-suffix $VERSION --output ./output /p:PackageVersion=$TAG_NAME
+      #         export PACKAGE_ID="${FOLDER_NAME}-${TAG_NAME}"
+      #         export PACKAGE_VERSION="${TAG_NAME}"
       #       else
-      #         echo "Error: Tags must be created on the main branch."
+      #         echo "Error: Tags must be created on the main."
       #         exit 1
       #       fi
-      #     elif [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
-      #       dotnet pack netapplication.csproj --configuration Release --version-suffix $VERSION --output ./output 
+      #     elif [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
+      #       export PACKAGE_ID="${FOLDER_NAME}"
+      #       export PACKAGE_VERSION="1.0.0-${GITHUB_RUN_ID}"
       #     elif [[ "${GITHUB_REF}" == "refs/heads/release" ]]; then
-      #       dotnet pack netapplication.csproj --configuration Release --version-suffix $SHORT_SHA --output ./output 
-      #     elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
+      #       COMMIT_ID=$(echo "${GITHUB_SHA}" | cut -c1-6)
+      #       export PACKAGE_ID="${FOLDER_NAME}-1.0.0-release-${COMMIT_ID}"
+      #       export PACKAGE_VERSION="1.0.0-release-${COMMIT_ID}"
+      #     else
+      #       echo "Error: Unsupported branch/tag for setting package name/version."
       #       exit 1
       #     fi
+
+      #     echo "PACKAGE_ID=${PACKAGE_ID}" >> $GITHUB_ENV
+      #     echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
+      #     echo "PACKAGE_ID: $PACKAGE_ID"
+      #     echo "PACKAGE_VERSION: $PACKAGE_VERSION"
+
+      # - name: Pack packages
+      #   run: |
+      #     dotnet pack netapplication.csproj --no-restore --no-build --configuration Release --output ${{ env.PACKAGE_OUTPUT_DIR }} \
+      #       /p:CustomPackageId=$PACKAGE_ID \
+      #       /p:PackageVersion=$PACKAGE_VERSION
+      #     ARTIFACT_PATH="${{ env.PACKAGE_OUTPUT_DIR }}/${PACKAGE_ID}.${PACKAGE_VERSION}.nupkg"
+      #     echo "ARTIFACT_PATH=${ARTIFACT_PATH}" >> $GITHUB_ENV
+      #     echo "Packaging completed. Artifact path: $ARTIFACT_PATH"
 
       # - name: Upload Package as Artifact
       #   uses: actions/upload-artifact@v3
       #   with:
       #     name: nuget-package
       #     path: ${{ env.ARTIFACT_PATH }}
-  
-
-      - name: Set package name and version  
-        id: set_name
-        shell: bash
-        run: |
-          echo "Checking GITHUB_REF: $GITHUB_REF"
-          git config --global --add safe.directory /__w/git-nexus-task/git-nexus-task
-          FOLDER_NAME="helloworld"
-
-          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
-            TAG_NAME="${GITHUB_REF#refs/tags/}"
-            git fetch --unshallow || true
-            MAIN_COMMIT=$(git rev-parse origin/main)
-            TAG_COMMIT=$(git rev-parse "${GITHUB_REF}")
-
-            if [[ "$TAG_COMMIT" == "$MAIN_COMMIT" ]]; then
-              export PACKAGE_ID="${FOLDER_NAME}-${TAG_NAME}"
-              export PACKAGE_VERSION="${TAG_NAME}"
-            else
-              echo "Error: Tags must be created on the main."
-              exit 1
-            fi
-          elif [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
-            export PACKAGE_ID="${FOLDER_NAME}"
-            export PACKAGE_VERSION="1.0.0-${GITHUB_RUN_ID}"
-          elif [[ "${GITHUB_REF}" == "refs/heads/release" ]]; then
-            COMMIT_ID=$(echo "${GITHUB_SHA}" | cut -c1-6)
-            export PACKAGE_ID="${FOLDER_NAME}-1.0.0-release-${COMMIT_ID}"
-            export PACKAGE_VERSION="1.0.0-release-${COMMIT_ID}"
-          else
-            echo "Error: Unsupported branch/tag for setting package name/version."
-            exit 1
-          fi
-
-          echo "PACKAGE_ID=${PACKAGE_ID}" >> $GITHUB_ENV
-          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
-          echo "PACKAGE_ID: $PACKAGE_ID"
-          echo "PACKAGE_VERSION: $PACKAGE_VERSION"
-
-      - name: Pack packages  
-        run: |
-          dotnet pack netapplication.csproj --no-restore --no-build --configuration Release --output ${{ env.PACKAGE_OUTPUT_DIR }} \
-            /p:CustomPackageId=$PACKAGE_ID \
-            /p:PackageVersion=$PACKAGE_VERSION
-          ARTIFACT_PATH="${{ env.PACKAGE_OUTPUT_DIR }}/${PACKAGE_ID}.${PACKAGE_VERSION}.nupkg"
-          echo "ARTIFACT_PATH=${ARTIFACT_PATH}" >> $GITHUB_ENV
-          echo "Packaging completed. Artifact path: $ARTIFACT_PATH"
-
-      - name: Upload Package as Artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: nuget-package
-          path: ${{ env.ARTIFACT_PATH }}
 
 
   SonarClouScan:
@@ -170,7 +176,7 @@ jobs:
       - name: Push to Nuget-snapshot Repository of Nexus          
         if: ${{ github.ref_name == 'dev' }}
         run: |
-          dotnet nuget push *.nupkg --source $NEXUS_SOURCE_DEV --api-key $NEXUS_API_KEY
+          dotnet nuget push ./output/netapplication.1.0.0-${{ github.run_id }}.nupkg --source $NEXUS_SOURCE_DEV --api-key $NEXUS_API_KEY
              
       - name: Pushing to Nuget-rc Repository of Nexus      
         if: ${{ github.ref_name == 'release' }}
