Updating main.yaml

diff --git a/.github/workflows/main-workflow.yaml b/.github/workflows/main-workflow.yaml
--- a/.github/workflows/main-workflow.yaml
+++ b/.github/workflows/main-workflow.yaml
@@ -41,37 +41,37 @@ jobs:
         run: |
              ls -l ./output
       
-      # - name: Check if the most recent commit is from the main branch
-      #   id: check_commit
-      #   run: |
-      #     git fetch origin main
-      #     MAIN_COMMIT=$(git rev-parse origin/main)
-      #     TAG_COMMIT=$(git rev-parse "${GITHUB_REF}")
-
-      #     if [[ "$TAG_COMMIT" == "$MAIN_COMMIT" ]]; then
-      #       echo "The most recent commit is from the main branch. Proceeding with deployment."
-      #       cd ./output
-      #       mv netapplication.1.0.0-${{ github.ref_name }}.nupkg netapplication.${{ github.ref_name }}.nupkg
-      #       ls -l
-      #       dotnet nuget push netapplication.${{ github.ref_name }}.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
-      #       exit 1
-      #     else
-      #       echo "The most recent commit is not from the main branch. Skipping deployment."
-      #     fi
-           
-           
-      
-      
-
-      - name: Push to Nuget-tag Repository of Nexus      
-        if: ${{ startsWith(github.ref, 'refs/tags/') }}
-        env:
-          NEXUS_SOURCE: http://faraztest.southeastasia.cloudapp.azure.com:8081/repository/nuget-tag/
+      - name: Check if the most recent commit is from the main branch
+        id: check_commit
         run: |
-          cd ./output
-          mv netapplication.1.0.0-${{ github.ref_name }}.nupkg netapplication.${{ github.ref_name }}.nupkg
-          ls -l
-          dotnet nuget push netapplication.${{ github.ref_name }}.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
+          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
+            TAG_NAME="${GITHUB_REF#refs/tags/}"
+
+            git fetch origin main
+            MAIN_COMMIT=$(git rev-parse origin/main)
+
+            TAG_COMMIT=$(git rev-parse "${GITHUB_REF}")
+
+            if [[ "$TAG_COMMIT" == "$MASTER_COMMIT" ]]; then
+              cd ./output
+              mv netapplication.1.0.0-${{ github.ref_name }}.nupkg netapplication.${{ github.ref_name }}.nupkg
+              ls -l
+              dotnet nuget push netapplication.${{ github.ref_name }}.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
+            else
+              echo "Error: Tags must be created on the master branch."
+              exit 1
+            fi
+          fi
+
+      # - name: Push to Nuget-tag Repository of Nexus      
+      #   if: ${{ startsWith(github.ref, 'refs/tags/') }}
+      #   env:
+      #     NEXUS_SOURCE: http://faraztest.southeastasia.cloudapp.azure.com:8081/repository/nuget-tag/
+      #   run: |
+      #     cd ./output
+      #     mv netapplication.1.0.0-${{ github.ref_name }}.nupkg netapplication.${{ github.ref_name }}.nupkg
+      #     ls -l
+      #     dotnet nuget push netapplication.${{ github.ref_name }}.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
 
       - name: Push to Nuget-snapshot Repository of Nexus
         if: ${{ github.ref_name == 'dev' }}
