Updating main.yaml

diff --git a/.github/workflows/main-workflow.yaml b/.github/workflows/main-workflow.yaml
--- a/.github/workflows/main-workflow.yaml
+++ b/.github/workflows/main-workflow.yaml
@@ -41,26 +41,23 @@ jobs:
         run: |
              ls -l ./output
       
-      - name: Push to Nuget-tag Repository of Nexus      
-        if: ${{ startsWith(github.ref, 'refs/tags/') }}
-        env:
-          NEXUS_SOURCE: http://faraztest.southeastasia.cloudapp.azure.com:8081/repository/nuget-tag/
+      - name: Check if the most recent commit is from the main branch
+        id: check_commit
         run: |
-
-          # Get the last 5 commits to check the most recent one
-          git log --oneline -n5
-          
-          # Check if the most recent commit is from the main branch
-          RECENT_COMMIT_BRANCH=$(git branch --contains $(git rev-parse HEAD) | grep -Eo 'main')
-          if [ "$RECENT_COMMIT_BRANCH" != "main" ]; then
-            echo "The most recent commit is not from the main branch. Skipping deployment."
-            exit 1
-          else
-            echo "The most recent commit is from the main branch. Proceeding with deployment."
-            cd ./output
-            mv netapplication.1.0.0-${{ github.ref_name }}.nupkg netapplication.${{ github.ref_name }}.nupkg
-            ls -l
-            dotnet nuget push netapplication.${{ github.ref_name }}.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
+          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
+            TAG_NAME="${GITHUB_REF#refs/tags/}"
+            git fetch origin main
+            MAIN_COMMIT=$(git rev-parse origin/main)
+            TAG_COMMIT=$(git rev-parse "${GITHUB_REF}")
+            if [[ "$TAG_COMMIT" == "$MAIN_COMMIT" ]]; then
+              cd ./output
+              mv netapplication.1.0.0-${{ github.ref_name }}.nupkg netapplication.${{ github.ref_name }}.nupkg
+              ls -l
+              dotnet nuget push netapplication.${{ github.ref_name }}.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
+            else
+              echo "Error: Tags must be created on the main branch."
+              exit 1
+            fi
           fi
 
       # - name: Push to Nuget-tag Repository of Nexus      
