Updating main2.yaml

diff --git a/.github/workflows/main-workflow_2.yaml b/.github/workflows/main-workflow_2.yaml
--- a/.github/workflows/main-workflow_2.yaml
+++ b/.github/workflows/main-workflow_2.yaml
@@ -30,8 +30,35 @@ jobs:
       - name: Pack the NuGet package
         run: |
           VERSION=${{ github.ref_name }}
-          dotnet pack netapplication.csproj --configuration Release --version-suffix $VERSION --output ./output       
-    
+          pwd
+          ls
+          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
+            TAG_NAME="${GITHUB_REF#refs/tags/}"
+                  
+            git fetch origin master
+            MASTER_COMMIT=$(git rev-parse origin/master)
+                  
+            TAG_COMMIT=$(git rev-parse "${GITHUB_REF}")
+                  
+            if [[ "$TAG_COMMIT" == "$MASTER_COMMIT" ]]; then
+              export PACKAGE_ID="nexus-git-${TAG_NAME}"
+              export PACKAGE_VERSION="${TAG_NAME}"
+            else
+              echo "Error: Tags must be created on the master branch."
+              exit 1
+            fi
+          elif [[ "${GITHUB_REF}" == "refs/heads/development" ]]; then
+            export PACKAGE_ID="${FOLDER_NAME}.nexus-git"
+            export PACKAGE_VERSION="1.0.0-${GITHUB_RUN_ID}"
+          elif [[ "${GITHUB_REF}" == "refs/heads/release" ]]; then
+            COMMIT_ID=$(echo "${GITHUB_SHA}" | cut -c1-6)
+            export PACKAGE_ID="nexus-git-1.0.0-release-${COMMIT_ID}"
+            export PACKAGE_VERSION="1.0.0-release-${COMMIT_ID}"
+          elif [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
+            exit 1
+          fi
+          ls
+       
       - name: List contents of output directory
         run: |
              ls -l ./output
