Updating main.yaml

diff --git a/.github/workflows/main-workflow.yaml b/.github/workflows/main-workflow.yaml
--- a/.github/workflows/main-workflow.yaml
+++ b/.github/workflows/main-workflow.yaml
@@ -38,6 +38,29 @@ jobs:
         run: |
              ls -l ./output
 
+      # - name: Push to Nuget-tag Repository of Nexus    
+      #   # if: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name == 'main' }}
+      #   if: ${{ startsWith(github.ref, 'refs/tags/') }}
+      #   env:
+      #     NEXUS_SOURCE: http://faraztest.southeastasia.cloudapp.azure.com:8081/repository/nuget-tag/
+      #   run: |
+      #     if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
+      #       TAG_NAME="${GITHUB_REF#refs/tags/}"
+      #       git fetch --unshallow || true
+      #       MAIN_COMMIT=$(git rev-parse origin/main)
+      #       TAG_COMMIT=$(git rev-parse "${GITHUB_REF}")
+
+      #       if [[ "$TAG_COMMIT" == "$MAIN_COMMIT" ]]; then
+      #         cd ./output
+      #         mv netapplication.1.0.0-${{ github.ref_name }}.nupkg netapplication.${{ github.ref_name }}.nupkg
+      #         ls -l
+      #         dotnet nuget push netapplication.${{ github.ref_name }}.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
+      #       else
+      #         echo "Error: Tags must be created on the main."
+      #         exit 1
+      #       fi
+      #     fi
+
       - name: Push to Nuget-tag Repository of Nexus    
         # if: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name == 'main' }}
         if: ${{ startsWith(github.ref, 'refs/tags/') }}
@@ -51,10 +74,18 @@ jobs:
             TAG_COMMIT=$(git rev-parse "${GITHUB_REF}")
 
             if [[ "$TAG_COMMIT" == "$MAIN_COMMIT" ]]; then
-              cd ./output
-              mv netapplication.1.0.0-${{ github.ref_name }}.nupkg netapplication.${{ github.ref_name }}.nupkg
-              ls -l
-              dotnet nuget push netapplication.${{ github.ref_name }}.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
+              echo "You are about to push the artifact to Nexus Repo 'Nuget-tag'."
+              read -p "Do you want to proceed? (YES/NO): " answer
+              if [[ "$answer" == "YES" ]]; then
+                echo "Proceeding with Nexus push..."
+                cd ./output
+                mv netapplication.1.0.0-${{ github.ref_name }}.nupkg netapplication.${{ github.ref_name }}.nupkg
+                ls -l
+                dotnet nuget push netapplication.${{ github.ref_name }}.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
+              else
+                echo "Push aborted by user."
+                exit 1
+              fi
             else
               echo "Error: Tags must be created on the main."
               exit 1
