Updating name in Release workflow

diff --git a/.github/workflows/release-workflow.yaml b/.github/workflows/release-workflow.yaml
--- a/.github/workflows/release-workflow.yaml
+++ b/.github/workflows/release-workflow.yaml
@@ -1,4 +1,4 @@
-name: release Workflow
+name: Release Workflow
 
 on:
   push:
@@ -41,26 +41,40 @@ jobs:
         run: |
              ls -l ./output
 
-      - name: Push to Nuget-tag Repository of Nexus
+      - name: Push to Nuget-tag Repository of Nexus 
         if: ${{ startsWith(github.ref, 'refs/tags/') }}
         env:
           NEXUS_SOURCE: http://faraztest.southeastasia.cloudapp.azure.com:8081/repository/nuget-tag/
         run: |
-          cd ./output
-          mv netapplication.1.0.0-${{ github.ref_name }}.nupkg netapplication.${{ github.ref_name }}.nupkg
-          ls -l
-          dotnet nuget push netapplication.${{ github.ref_name }}.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
+          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
+            TAG_NAME="${GITHUB_REF#refs/tags/}"
+            git fetch --unshallow || true
+            MAIN_COMMIT=$(git rev-parse origin/main)
+            TAG_COMMIT=$(git rev-parse "${GITHUB_REF}")
 
-      - name: Push to Nuget-snapshot Repository of Nexus
+            if [[ "$TAG_COMMIT" == "$MAIN_COMMIT" ]]; then
+              cd ./output
+              mv netapplication.1.0.0-${{ github.ref_name }}.nupkg netapplication.${{ github.ref_name }}.nupkg
+              ls -l
+              dotnet nuget push netapplication.${{ github.ref_name }}.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
+            else
+              echo "Error: Tags must be created on the main."
+              exit 1
+            fi
+          fi
+
+          
+          
+      - name: Push to Nuget-snapshot Repository of Nexus          
         if: ${{ github.ref_name == 'dev' }}
         env:
           NEXUS_SOURCE: http://faraztest.southeastasia.cloudapp.azure.com:8081/repository/nuget-snapshot/
         run: |
-          cd ./output
-          mv netapplication.1.0.0.nupkg netapplication.${{ github.ref_name }}-${{ github.job }}.nupkg
-          dotnet nuget push netapplication.${{ github.ref_name }}-${{ github.job }}.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
+            cd ./output
+            mv netapplication.1.0.0.nupkg netapplication.dev-build.nupkg
+            dotnet nuget push netapplication.dev-build.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
       
-      - name: Pushing to Nuget-rc Repository of Nexus
+      - name: Pushing to Nuget-rc Repository of Nexus      
         if: ${{ github.ref_name == 'release' }}
         env:
           NEXUS_SOURCE: http://faraztest.southeastasia.cloudapp.azure.com:8081/repository/nuget-rc/
